/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://mvfedn45v5d6fl3fljtxbw66ue.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-hy6h4t35m5gaho7qgmvu2z7rzu",
    "aws_cognito_identity_pool_id": "us-east-1:6fc29f46-53d6-4e01-b8e2-ce3e6f5544f9",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_csgxO1u0T",
    "aws_user_pools_web_client_id": "2q3dslsr34elnhrpu3aec24pvt",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
